models:
    container_name: models
    image: tp33/django
    volumes:
        - ./models:/app
    command: bash -c "python /app/manage.py makemigrations api; python /app/manage.py migrate; python manage.py flush --no-input; python manage.py loaddata /app/sentence.json /app/article.json /app/comment.json /app/image.json; mod_wsgi-express start-server --working-directory /app --reload-on-change models/wsgi.py"
    ports:
        - "8000:8000"

web:
    container_name: web
    image: tp33/django
    volumes:
        - ./web:/app
    command: bash -c "mod_wsgi-express start-server --working-directory /app --reload-on-change web/wsgi.py"
    ports:
        - "80:8000"
    links:
        - models:models-api
